version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mariadb:10.4.24
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3307:3306" # bên ngoài connect qua 3307
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      # - frontend
    networks:
      - app-network
  redis:
    image: redis:7.0
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
  es_data:
