version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      # - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
